security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Sdz\UserBundle\Entity\User: 
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:             [ROLE_ADMIN, ROLE_MANAGER]
        ROLE_SUPER_ADMIN:       ROLE_ADMIN

    providers:
        main:
            entity:
                class:    Sdz\UserBundle\Entity\User
                property: username
                manager_name: user

    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path:         /api/login_check
                success_handler:    lexik_jwt_authentication.handler.authentication_success
                failure_handler:    lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern:   ^/login$
            anonymous: true

        reset_pass:
            pattern:   ^/resetpassword
            anonymous: true

        main:
            pattern:   ^/
            anonymous: false
            provider:  main
            guard:
                authenticators:
                    - sdz_user.tokenauthenticator
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: user
                use_referer: true
            logout:
                path:   logout
                target: /login

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
