<?php

namespace DowngradingBundle\Repository;

/**
 * DowngradingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DowngradingRepository extends \Doctrine\ORM\EntityRepository
{
}
