<?php

namespace DiagnosticBundle\Repository;

/**
 * InspectionVisuelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InspectionVisuelleRepository extends \Doctrine\ORM\EntityRepository
{
}
