<?php

namespace DiagnosticBundle\Repository;

/**
 * InternInspectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternInspectionRepository extends \Doctrine\ORM\EntityRepository
{
}
