<?php

namespace DiagnosticBundle\Repository;

/**
 * IsolementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IsolementRepository extends \Doctrine\ORM\EntityRepository
{
}
