<?php

namespace DiagnosticBundle\Repository;

/**
 * TransformerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransformerRepository extends \Doctrine\ORM\EntityRepository
{
}
