<?php

namespace DiagnosticBundle\Repository;

/**
 * TurnRatioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurnRatioRepository extends \Doctrine\ORM\EntityRepository
{
}
