<?php

namespace ThirdPartyBundle\Repository;

/**
 * ThridPartyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThirdPartyRepository extends \Doctrine\ORM\EntityRepository
{
}
