reset_password:
    path:     /
    defaults: { _controller: "SdzUserBundle:Security:reset_password" }
    requirements: { _method: get }

reset_password_send_email:
    path:     /send_email
    defaults: { _controller: "SdzUserBundle:Security:send_email" }
    requirements: { _method: post|put }

reset_password_check_email:
    path:     /{id}/check_email
    defaults: { _controller: "SdzUserBundle:Security:check_email" }
    requirements: { _method: post|put }

reset_password_update:
    path:     /{id}/update
    defaults: { _controller: "SdzUserBundle:Security:update" }
    requirements: { _method: post|put }

reset_password_edit:
    path:     /{id}/edit
    defaults: { _controller: "SdzUserBundle:Security:edit" }
    requirements: { _method: get }

reset_password_logout:
    path:     /logout1/{id}
    defaults: { _controller: "SdzUserBundle:Security:logout1" }
    requirements: { _method: get }